services:
  - type: web
    name: transformer-response-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn drive_model:app
    envVars:
      - key: PORT
        value: 5000
