services:
  - type: web
    name: transformer-response-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python your_script_name.py
    envVars:
      - key: PORT
        value: 5000
